# Generated by Django 3.2 on 2023-07-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.ImageField(blank=True, default='blog_image/default.png', null=True, upload_to='blog_image')),
                ('blog_title', models.CharField(max_length=35)),
                ('blog_creation_date', models.DateTimeField()),
                ('blog_text', models.TextField(max_length=70)),
            ],
        ),
    ]
