# Generated by Django 3.2 on 2023-07-10 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.ImageField(blank=True, default='blog_image/default.png', null=True, upload_to='blog_image')),
                ('blog_title', models.CharField(max_length=35)),
                ('blog_creation_date', models.DateTimeField()),
                ('blog_text', models.TextField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_image', models.ImageField(blank=True, default='room_image/default.png', null=True, upload_to='room_image')),
                ('hotel_type', models.CharField(max_length=50)),
                ('Adults', models.IntegerField()),
                ('price', models.PositiveBigIntegerField()),
                ('categories', models.CharField(max_length=10)),
                ('size', models.IntegerField(default=20)),
                ('Facilities', models.TextField(max_length=130)),
                ('beds', models.CharField(blank=True, max_length=15, null=True)),
                ('additional_offer', models.CharField(blank=True, max_length=21, null=True)),
            ],
            options={
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luxry.rooms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
