# Generated by Django 3.2 on 2023-07-13 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luxry', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
